# Generated by Django 4.0.3 on 2022-04-03 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Red Social')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('age', models.CharField(choices=[('18-25', ' 18-25'), ('26-33', '26-33'), ('34-40', '34-40'), ('40+', '40+')], default='18-25', max_length=15, verbose_name='Edad')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
                ('time_avg_facebook', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo promedio en Facebook')),
                ('time_avg_whatsapp', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo promedio en Whatsapp')),
                ('time_avg_twitter', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo promedio en Twitter')),
                ('time_avg_instagram', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo promedio en Instagram')),
                ('time_avg_tiktok', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo promedio en Tiktok')),
                ('favorite_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.socialnetwork', verbose_name='Red Social')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
